services:
  front-site:
    build: ./front
    container_name: front
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    restart: unless-stopped
  
  backoffice:
    build: ./backoffice
    container_name: backoffice
    ports:
      - "5174:5174"
    command: npm run dev -- --host
    restart: unless-stopped